namespace: marooncap
name: k3s_ansible
version: 1.4.0
readme: README.md
authors:
  - your name <example@domain.com>
description: >
  The easiest way to bootstrap a self-hosted High Availability Kubernetes
  cluster. A fully automated HA k3s etcd install with kube-vip, MetalLB, and
  more.
license:
  - Apache-2.0
tags:
  - etcd
  - high-availability
  - k8s
  - k3s
  - k3s-cluster
  - kube-vip
  - kubernetes
  - metallb
  - rancher
dependencies:
  ansible.utils: '*'
  ansible.posix: '*'
  community.general: '*'
  kubernetes.core: '*'
repository: https://github.com/marooncap/k3s-ansible
documentation: https://github.com/marooncap/k3s-ansible
homepage: https://www.youtube.com/watch?v=CbkEWcUZ7zM
issues: https://github.com/marooncap/k3s-ansible/issues
build_ignore: []
