---
- name: Create manifests directory on first master
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']

- name: Download longhorn manager manifest to first master
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/longhorn/longhorn/{{ longhorn_manager_tag_version | default('master') }}/deploy/longhorn.yaml # noqa yaml[line-length]
    dest: /var/lib/rancher/k3s/server/manifests/longhorn.yaml
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
